#!/usr/bin/env bash
# Write a Bash script that stops 4-to_infinity_and_beyond process.

#here find the PID
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

#here kill the unique id set above
if [ -n "$id" ]
then
  kill -15 "$id"
fi
